id: P000749
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:40:48.746241
source_metadata:
  id: bdr:W1KG25092
  title: མངོན་བརྗོད་རྒྱ་མཚོའི་ཆུ་ཐིགས་ཀྱི་རྩ་འགྲེལ།
  author: ''
  volumes:
    7def615baf7a4ea3ade687d29c98d167:
      image_group_id: I1KG25094
      title: ''
      volume_number: 1
      total_pages: 338
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
